### ISSUE TITLE
Win93 question?

### ISSUE THREAD

**Issue by Busybody64** [Driftini/driftini.github.io#5]
Do you think you'll ever try making a windows 93 browser again? 

Preferably NOT one that requires any extensions to work, but still...

**Comment by Driftini** [comment]
Sorry, but I've lost interest in Windows93 app development. Plus, looking back, the whole concept of a browser for a "web OS" is admittedly really stupid.
Guess that's just the kind of stuff you end up making when you're 12 and just find out about JavaScript.
